In [3]:
import numpy as np

# Data

In [4]:
data_lists_of_lists = [[0,5,1],
                        [0,2,0],
                        [1,1,2],
                        [2,2,1],
                        [0,0,0]]


arr=np.array(data_lists_of_lists)
arr

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

# Aggregating methods

* sum()
* min()
* max()
* mean()
* cunsum()


# Summing Data
The aggregating method, .sum, adds up all elements in the entire array.

In [5]:
arr.sum()

17

## Summing rows

Setting axis equal to one will sum the values of all columns in each row, creating row totals. Here, the totals represent the security breaches experienced by all clients in a given year

In [6]:
arr.sum(axis=0)

array([ 3, 10,  4])

## Summing columns

In [7]:
arr.sum(axis=1)

array([6, 2, 4, 5, 0])