# Vectorized operations

In [2]:
import numpy as np

In [3]:
array = [
    [1,2,3],
    [4,5,5],
   ]

arr1 = np.array(array)
arr1

array([[1, 2, 3],
       [4, 5, 5]])

In [4]:
#Array  dimensions
arr1.shape

# arr1.shape[0] --> Rows
# arr1.shape[1] -- > Columns

(2, 3)

## Sum Comparison: NumPy & Python

### Syntax in python

In [5]:
for row in range(arr1.shape[0]):
	for column in range(arr1.shape[1]):
		arr1[row][column] += 3

In [6]:
arr1

array([[4, 5, 6],
       [7, 8, 8]])

### Syntax NumPy

In [7]:
arr2 = np.array(array)

In [8]:
sum = arr2 +3
sum

array([[4, 5, 6],
       [7, 8, 8]])

## Multiplying by a scalar

In [9]:
arr3 = np.array(array)
arr3 * 3

array([[ 3,  6,  9],
       [12, 15, 15]])

## Adding two arrays (same shape)

In [10]:
array_a = np.array([[1, 2, 3],[4, 5, 6]])
array_b = np.array([[0, 1, 0],[1, 0, 1]])

print("Sum: ")
print(array_a + array_b)

Sum: 
[[1 3 3]
 [5 5 7]]


## Multiplying two arrays

In [11]:
# array_a = np.array([[1, 2, 3],[4, 5, 6]])
# array_b = np.array([[0, 1, 0],[1, 0, 1]])

print("Result: ")
print(array_a * array_b)

Result: 
[[0 2 0]
 [4 0 6]]


## Boolean maks | Filter arrays

In [12]:
array_bl = np.array([[1, 2, 3],[4, 5, 6]])
array_bl > 2

array([[False, False,  True],
       [ True,  True,  True]])

# Vectorize Python code

We can even create our own vectorized functions from Python functions using np-dot-vectorize. For example, let's check whether each string element in an array has a length greater than two. But this doesn't work; instead, the code returns True, because the array has more than two elements.

Len is a python function not a NumPy function, so it can't vectorize.
We need to vectorized this.

In [13]:
array_v = np.array (["NumPy", "is", "awesome"])
len(array_v) > 2

True

## Vectorized

In [14]:
vectorized_len = np.vectorize(len)

In [15]:
vectorized_len(array_v) > 2

array([ True, False,  True])