# Array indexing

Indexing is an order-based method for accessing data. NumPy indexing is zero-based, meaning the first index is index zero. Array indexing uses square brackets, similar to indexing Python lists.

When indexing a 2D array, give NumPy both a row and column index in order to return a single element.

**References**
* DataCamp - Introduction to NumPy

In [1]:
import numpy as np

# Indexing 1D Arrays

```
# This is formatted as code
```



In [2]:
# Example 1
arr1d1 = np.array([2,4,6,8,10])
arr1d1

array([ 2,  4,  6,  8, 10])

In [4]:
arr1d1[3]

8

In [5]:
arr1d1[1]

4

# Indexing 2D Arrays

In [11]:
# Example 1-  2-D Array
arr2d1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr2d1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
type(arr2d1)

numpy.ndarray

In [16]:
arr2d1[1,1]

array([4, 5, 6])

## Sudoku game

For example, to get the value in the third row of the fifth column, we provide both the row index, two, and the column index, four. Here, like everywhere else in NumPy, row information comes before column information.

In [18]:
# Example 2
sudoku_list =[
 [0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]


In [19]:
# Convert sudoku_list into an array
sudoku_array = np.array(sudoku_list)

# Print the type of sudoku_array
print(type(sudoku_array))

<class 'numpy.ndarray'>


In [20]:
sudoku_array[2,4]

6

In [21]:
# Index the first row
sudoku_array[0]

array([0, 0, 4, 3, 0, 0, 2, 0, 9])

In [22]:
# Index the fourth colum
sudoku_array[:,3]

array([3, 0, 0, 0, 0, 0, 0, 5, 9])