# Array Slicing

Slicing extracts a subset of data based on given indices from one array and creates a new array with the sliced data. To slice, provide a start and stop value, separated by a colon and enclosed in square brackets. The element at the start index is included in the result, but the one at the stop index is not: here, the number 10 at index four is excluded from the result.

**References**
* DataCamp - Introduction to NumPy

In [1]:
import numpy as np

# Slicing 1D Arrays


In [4]:
# Example 1
arr1d1 = np.array([2,4,6,8,10])
arr1d1

array([ 2,  4,  6,  8, 10])

In [5]:
arr1d1[2:4]

array([6, 8])

# Slicing 2D Arrays

## Sudoku game

For example, to get the value in the third row of the fifth column, we provide both the row index, two, and the column index, four. Here, like everywhere else in NumPy, row information comes before column information.

In [6]:
# Example 2
sudoku_list =[
 [0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]


In [7]:
# Convert sudoku_list into an array
sudoku_array = np.array(sudoku_list)

# Print the type of sudoku_array
print(type(sudoku_array))

<class 'numpy.ndarray'>


### Indexing

In [ ]:
sudoku_array[2,4]

6

In [ ]:
# Index the first row
sudoku_array[0]

array([0, 0, 4, 3, 0, 0, 2, 0, 9])

In [ ]:
# Index the fourth colum
sudoku_array[:,3]

array([3, 0, 0, 0, 0, 0, 0, 5, 9])

### Slicing

In [8]:
sudoku_array[3:6, 3:6]

array([[0, 0, 2],
       [0, 0, 7],
       [0, 8, 3]])

In [9]:
# Slicing with steps
sudoku_array[3:6:2, 3:6:2]

array([[0, 2],
       [0, 3]])