# Array Creation

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`. We can create a NumPy `ndarray` object by using the `array()` function.


In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Creating Arrays with defined Data Type

We use the `array()` function to create arrays, this function can take an optional argument: `dtype` that allows us to define the expected data type of the array elements:

### Example 1
Array with data type string:

In [3]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


### Example 2
Array with data type 4 bytes integer:

In [4]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

**nested array:** are arrays that have arrays as their elements.



* **0-D arrays**, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
* **1-D array:** An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
* **2-D array:** An array that has 1-D arrays as its elements is called a 2-D array.
  * These are often used to represent matrix or 2nd order tensors.
  * NumPy has a whole sub module dedicated towards matrix operations called `numpy.mat`
* **3-D array:** An array that has 2-D arrays (matrices) as its elements is called 3-D array.

### Examples of arrays

In [18]:
# 0 D array
arr1 = np.array(42)

# 1 D array
arr2 = np.array([1, 2, 3, 4, 5])

# 2D Arrays
arr3 = arr = np.array([[1, 2, 3], [4, 5, 6]]) 

# 3D Arrays
arr4 = arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) 

### 1-D Array

In [19]:
# Example 1
arr1d1 = np.array([1, 2, 3, 4, 5])
arr1d1

array([1, 2, 3, 4, 5])

In [20]:
# Example 2 - From a list
python_list = [3,2,5,8,4,9,7,6,1]
arr1d2 = np.array(python_list)
arr1d2


array([3, 2, 5, 8, 4, 9, 7, 6, 1])

In [21]:
type(arr1d2)

numpy.ndarray

### 2-D Array

In [22]:
# Example 1-  2-D Array
arr2d3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr2d3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [23]:
# Example 2- 2-D Array
python_lists_of_lists = [[3, 2, 5],
                        [9, 7, 1],
                        [4, 3, 6]]

arr2d4=np.array(python_lists_of_lists)
arr2d4

array([[3, 2, 5],
       [9, 7, 1],
       [4, 3, 6]])

In [8]:
type(arr2d4)

numpy.ndarray

In [9]:
# Example 3
sudoku_list=[[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]

In [10]:
# Convert sudoku_list into an array
sudoku_array = np.array(sudoku_list)

# Print the type of sudoku_array
print(type(sudoku_array))

<class 'numpy.ndarray'>


### Check Number of Dimensions

#### Numpy.ndim
NumPy Arrays provides the `ndim` attribute that returns an integer that tells us how many dimensions the array have.

In [14]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Numpy.shape
Return the shape of an array

##### 1D arrays
###### Example 1

In [17]:
print(np.shape(np.eye(3)))
print(np.shape([[1, 3]]))
print(np.shape([0]))
print(np.shape(0))

(3, 3)
(1, 2)
(1,)
()


###### Example 2

1 D array
```python
arr1d1 = np.array([1, 2, 3, 4, 5])
```

In [28]:
print(arr1d1.shape[0])

5


##### 2D arrays
```python
# 2D Arrays
arr3 = arr = np.array([[1, 2, 3], [4, 5, 6]]) 
```

In [30]:
print(arr3.shape[0])#--> Rows
print(arr3.shape[1]) #-- > Columns


2
3


## Initializing different types of arrays

### Arrays of Zeros

In [11]:
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Arrays of Ones

In [12]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Random numbers

In [14]:
# Random numbers between zero and one
arr_random = np.random.random(10)
arr_random

array([0.53544433, 0.12022352, 0.41248733, 0.55743943, 0.42757129,
       0.65476639, 0.51052861, 0.42894404, 0.29394554, 0.18140074])

### Random numbers - Normal distribution

In [15]:
# Numbers that are distributed according to a Gaussian distribution with a mean of zero and a standard deviation of one
arr_randn = np.random.randn(10)
arr_randn

array([-3.06276391, -0.1496384 ,  1.01552167,  1.78931753, -0.45265291,
       -1.39060766, -0.79791656, -0.96053735, -0.20239184, -2.92464304])

### Numbers with equal space

```python
np.linspace(start, stop, num)
```
* start: The starting value of the sequence.
* stop: The ending value of the sequence.
* num: The number of evenly spaced values to generate between start and stop (inclusive).

In [16]:
# Numbers that range from 0 to 10. Elements are equally spaced apart from 0 to 100
arr_linspace= np.linspace(0,10,100)
arr_linspace

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Create a range of numbers

'array = np. arange(start, final, spacing)'

In [17]:

arr_arange=np.arange(0,10,0.02)
arr_arange

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  , 1.02, 1.04, 1.06, 1.08,
       1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22, 1.24, 1.26, 1.28, 1.3 ,
       1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44, 1.46, 1.48, 1.5 , 1.52,
       1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66, 1.68, 1.7 , 1.72, 1.74,
       1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88, 1.9 , 1.92, 1.94, 1.96,
       1.98, 2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18,
       2.2 , 2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 ,
       2.42, 2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62,
       2.64, 2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84,
       2.86, 2.88, 2.9 , 2.92, 2.94, 2.96, 2.98, 3.

# REFERENCES


## YouTube
* NumPy Tutorial (2022): For Physicists, Engineers, and Mathematicians: https://youtu.be/DcfYgePyedM

## Websites
### FreeCodeCamp
	* Python NumPy Tutorial for Beginners
	* https://youtu.be/QUT1VHiLmmI
	
### Programiz
* https://www.programiz.com/python-programming/numpy/basic-array-operations

### W3schools
* https://www.w3schools.com/python/numpy
* https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp

## DataCamp
*  [[Introduction to NumPy]]

## Books
* 2022 - Wes McKinney - Python for Data Analysis 