# Array Sorting

The np-dot-sort function sorts an array along a given axis. Here, NumPy has sorted the array along the columns, with the highest number from each row in the far right.

We also can sort by row by using axis labels.

**References**
* DataCamp - Introduction to NumPy

In [1]:
import numpy as np

# Sorting 1D Arrays


In [2]:
# Example 1
arr1d1 = np.array([2,6,4,8,10])
arr1d1

array([ 2,  6,  4,  8, 10])

In [4]:
np.sort(arr1d1)

array([ 2,  4,  6,  8, 10])

# Slicing 2D Arrays

## Sudoku game

For example, to get the value in the third row of the fifth column, we provide both the row index, two, and the column index, four. Here, like everywhere else in NumPy, row information comes before column information.

In [6]:
# Example 2
sudoku_array = np.array([
 [0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]])

sudoku_array


array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

### Indexing

In [ ]:
sudoku_array[2,4]

6

In [ ]:
# Index the first row
sudoku_array[0]

array([0, 0, 4, 3, 0, 0, 2, 0, 9])

In [ ]:
# Index the fourth colum
sudoku_array[:,3]

array([3, 0, 0, 0, 0, 0, 0, 5, 9])

### Slicing

In [ ]:
sudoku_array[3:6, 3:6]

array([[0, 0, 2],
       [0, 0, 7],
       [0, 8, 3]])

In [ ]:
# Slicing with steps
sudoku_array[3:6:2, 3:6:2]

array([[0, 2],
       [0, 3]])

### Sorting

The np-dot-sort function sorts an array along a given axis. Here, NumPy has sorted the array along the columns (axis=1), with the highest number from each row in the far right.

The default axis in np-dot-sort is the last axis of the array passed to it. If a 2D array is being sorted, NumPy sorts by columns, since columns are axis 1 and rows are axis 0.


In [7]:
np.sort(sudoku_array)

array([[0, 0, 0, 0, 0, 2, 3, 4, 9],
       [0, 0, 0, 0, 0, 0, 1, 5, 9],
       [0, 0, 0, 0, 0, 3, 4, 6, 7],
       [0, 0, 0, 0, 0, 2, 6, 7, 8],
       [0, 0, 0, 0, 0, 1, 4, 7, 9],
       [0, 0, 0, 0, 0, 0, 3, 5, 8],
       [0, 0, 0, 0, 0, 0, 1, 5, 6],
       [0, 0, 0, 0, 3, 5, 6, 8, 9],
       [0, 0, 0, 0, 1, 2, 3, 4, 9]])

### Sorting along the rows

In [8]:
np.sort(sudoku_array, axis=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 2, 1, 0, 1],
       [0, 4, 3, 0, 0, 3, 2, 0, 3],
       [0, 5, 4, 3, 1, 7, 3, 4, 5],
       [1, 7, 5, 5, 6, 8, 4, 8, 7],
       [6, 9, 6, 9, 8, 9, 6, 9, 9]])